export const apps = [
	{ id: '1', name: 'Projects', icon: '/icons/crab.png' },
	{ id: '2', name: 'Skills', icon: '/icons/fish.png' },
	{ id: '3', name: 'Contact', icon: '/icons/jellyfish.png' },
	{ id: '4', name: 'Recycle Bin', icon: '/icons/starfish.png' },
	{ id: '5', name: 'Projects', icon: '/icons/crab.png' },
	{ id: '6', name: 'Skills', icon: '/icons/fish.png' },
	{ id: '7', name: 'Contact', icon: '/icons/jellyfish.png' },
	{ id: '8', name: 'Projects', icon: '/icons/crab.png' },
	{ id: '9', name: 'Skills', icon: '/icons/fish.png' },
	{ id: '10', name: 'Contact', icon: '/icons/jellyfish.png' },
	{ id: '11', name: 'Projects', icon: '/icons/crab.png' },
	{ id: '12', name: 'Skills', icon: '/icons/fish.png' },
	{ id: '13', name: 'Contact', icon: '/icons/jellyfish.png' },
	{ id: '14', name: 'Projects', icon: '/icons/crab.png' },
	{ id: '15', name: 'Skills', icon: '/icons/fish.png' },
	{ id: '16', name: 'Contact', icon: '/icons/jellyfish.png' },
	{ id: '17', name: 'Projects', icon: '/icons/crab.png' },
	{ id: '18', name: 'Skills', icon: '/icons/fish.png' },
	{ id: '19', name: 'Contact', icon: '/icons/jellyfish.png' },
]
